site_name: Open Ocean Software
site_url: https://oceansoft.org
theme:
  name: material
  palette:
    primary: blue grey
    accent: indigo
  font:
    text: "Lora"
  logo: assets/openocean-logo-no-text.svg

  features:
  - announce.dismiss
  favicon: assets/favicon.png

nav:
    - Home: index.md
    - team.md
    - Project Directory: directory/index.md
    - Submit a Project: directory-submit/index.md
    - ros-maritime-survey.md

plugins:
  - search
  - macros:
      include_yaml:
        - data/projects.yml

markdown_extensions:
- attr_list
- md_in_html
- admonition
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji ""
    emoji_generator:

      !!python/name:material.extensions.emoji.to_svg ""

extra_css:
  - stylesheets/directory.css

extra:
  social:
  - icon: fontawesome/brands/discourse
    link: https://forum.oceansoft.org
  - icon: fontawesome/brands/github
    link: https://github.com/openocean-software/
  generator: false
